### PR TITLE
Adding loom provider docs

### PR DESCRIPTION
**Pull request by eduardonunesp**

### CODE REVIEW

**Comment by enlight** [comment]
Can you add the sample code to https://github.com/loomnetwork/loom-js-samples ?

**Comment by mattkanwisher** [comment]
@eduardonunesp is the contract always 000000? shouldn't it have an address? what if there are multiple solidity contracts?

**Comment by eduardonunesp** [comment]
@mattkanwisher I'll make some changes today after the updates on `go-loom` I have some stuff to fix on this docs too

**Comment by mattkanwisher** [comment]
@eduardonunesp  updates ?

**Pull request merged**
